services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8           # Mac M1/M2
    container_name: vinfast-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tuyettram01
      MYSQL_DATABASE: VinFast_EVM_Warranty1
      # (tuỳ chọn) tạo user riêng thay vì dùng root:
      # MYSQL_USER: app
      # MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptuyettram01"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: