package com.warrantyclaim.warrantyclaim_api.repository;

import com.warrantyclaim.warrantyclaim_api.entity.ProductsSparePartsTypeEVMWarrantyPolicy;
import com.warrantyclaim.warrantyclaim_api.entity.ProductsSparePartsTypeEVMWarrantyPolicyId;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductsSparePartsTypeEVMWarrantyPolicyRepository extends JpaRepository<ProductsSparePartsTypeEVMWarrantyPolicy, ProductsSparePartsTypeEVMWarrantyPolicyId> {
}
